---
title: "Mecánica de Lanzamiento"
subtitle: "Pesca con mosca"
---

Te doy la bienvenida a esta pasión que es la pesca con mosca. Además de conocer una modalidad maravillosa, también te va a permitir conocer un estilo de vida.

-   Clases teórico-prácticas (2h duración)

-   Días y horarios flexibles

-   Lugar a convenir

-   Sin experiencia previa

-   No hace falta contar con equipos

-   Recursos gráficos y audiovisuales

-   Contenidos según nivel: Inicial - Medio - Avanzado

# Temario

## Principios del lanzamiento

Todo lanzamiento que uno vaya a efectuar independientemente cual sea, será efectivo si están presentes todo los principios que permitirán que se logre dicho *cast*. Un *cast* con la ausencia de uno de los principios, lo condenaría al fracaso, por no respetar y/o entender la física del lanzamiento. Un principio es una regla que debe seguirse con el fin de lograr cierto propósito específico y un conjunto de principios son las reglas a seguir para lograr un fin mayor. El objetivo es saber si están bien claros, definidos e incluidos los pasos del lanzamiento, corrigiendo en cada *cast* la mecánica de los movimientos. Un buen lanzamiento tiene como fin depositar la mosca en el agua con la mayor delicadeza y precisión posible y en la menor cantidad de movimientos.

### Tensión de la línea

Debe tener la línea tensa siempre antes de iniciar cualquier *cast* para poder cargar la caña apropiadamente, ya que al tener tensión en la línea la puntera cuando se empieza a mover, literalmente tira de la línea y la masa de esta detiene o retrasa la puntera obligándola a doblarse justo ahí en la punta de la caña. Siempre observe si al iniciar un *cast* está tirando de la línea con la puntera y si esta se retrasa y se dobla en cuanto empieza el movimiento y de no ser así es porque su línea no estaba tensa al momento de iniciarlo y habrá tirado simplemente de una línea floja y la caña no se doblara hasta que la línea no se tense. La falta de tensión además de obligar al *caster* a hacer movimientos más rápidos, lo que genera cansancio, *loops* muy abiertos u ondas indeseadas en la línea. Tensión de línea carga la caña eficientemente y le da control de la línea.

### Aceleración gradual y constante

Todo cast debe tener una aceleración contante y creciente hasta la parada. La única manera de cargar la caña eficientemente es teniendo tensión de línea y moviendo la mano y brazo lanzador. La caña con velocidad creciente durante todo el golpe de lanzado, muy lento al comienzo, mas rápido en el medio del golpe y a la máxima velocidad requerida sobre el final del cast. Si tiene una aceleración constante, la velocidad irá aumentando a medida que evolucione el lanzado y es en el instante previo a la parada en donde tendrá la máxima velocidad en la puntera de la caña. Empiece como una tortuga y termine como una liebre su golpe de lance, eso le permitirá tener una aceleración apropiada. Aceleración gradual y constante: carga la caña eficientemente, evita hondas en la linea , nudos indeseados en el líder y logra una velocidad en aumento permanente sin esfuerzo.

### Acto de lanzamiento variable

El arco de lanzamiento se varía por dos aspectos:

1.  El tamaño del arco de lanzamiento con respecto a la cantidad de línea en vuelo.

2.  La ubicación del arco de Lanzamiento según distancia del cast, viento y el tipo representación que quiera hacerse.

La definición que más se lee y escucha de **Arco de Lanzamiento** es la siguiente:

> *Se trata de la distancia que recorre la puntera de la caña entre parada y parada, entendiéndose como el ángulo que describe el talón de la caña entre parada y parada.*

Este es el sello distintivo de todo buen lanzador independientemente del estilo que tenga, ya que todo buen lanzador ajusta el tamaño del arco según la situación de pesca requerida, porque es lo que determina si el loop será angosto o amplio o si tendrá un loop cruzado. Debemos saber que siempre la línea sigue la trayectoria de la puntera, por lo cual el loop es el resultado de dicha trayectoria. Para controlar diferentes trayectorias de la puntera de la caña durante el lanzamiento y, por ende, diferentes loops, debemos entender perfectamente este principio. Quien lo desconozca jamás tendrá el control de línea que desea.

De esta manera, los Loop cerrados se producen siempre que la trayectoria de la puntera es rectilínea, mientras que los Loops abiertos se producen cuando la trayectoria de la puntera es convexa o parabólica ascendente. Por otro lado, los Loops cruzados o tailing loops se producen cuando la trayectoria de la puntera es cóncava o descendente.Tambien profundizaremos sobre los Cast corto arco corto, cast medio arco medio, cast largo arco largo.

Veremos definiciones imporantes

> **Loops abiertos:** deben generar una trayectoria PARABÓLICA O CONVEXA DE LA PUNTERA. Para lograr esto se debe aumentar el tamaño del arco de lanzamiento con respecto a la cantidad de línea volada. Lo que aprenderemos es que de esta manera la puntera no viajara en línea recta, sino que lo hará en forma semi circular hacia arriba.

Los loops abiertos son ideales para pescar con ninfas grandes, lastre y grandes streamers como las moscas de Dorado, Tarariras o algunas de Salt Water.

> **Loops cruzados o tailling Loops**: se producen porque el arco de lanzamiento es menor al que se necesita para ese cast en particular. Es decir, el arco fue corto en relación a la cantidad de línea volada o por una aceleración errática.

En este caso, lo que sucede es que la puntera abandona la trayectoria rectilínea que debería tener (causa) y produce un trayectoria cóncava o curva hacia abajo obligando a que la línea haga lo mismo (efecto). Aqui el ramal superior o de la mosca cruza visiblemente el ramal inferior o de la caña y es ahí en donde se producen nudos en nuestra líder. Esto generaría algo que muchos pescadores lo padecen a diario, mal llamados nudos de viento. Este no interviene en el suceso. Este error se puede resolver fácilmente: si tiene problemas con los tailing loop, amplié el tamaño de su arco de lanzamiento y acelere suavemente y de manera constante durante todo el golpe de lance, vera que los loops cruzados desaparecen.

### Timing o tempo del lanzado

Para tener un buen timing o tempo del lanzado, debe hacer la pausa necesaria, para que la línea se estire totalmente antes de empezar el lanzamiento en la dirección opuesta. La pausa justa en el casteo es vital para asegurarse siempre de estar trabajando con línea tensa. Si tiene problemas con su tempo, debe determinar si es porque no espera a que la línea se estire por completo o si es porque espera demasiado y la linea se cae en un back cast. En los dos casos el resultado es el mismo, perdida de tensión de línea, lo que no le permite cargar la caña apropiadamente y tener el control deseado sobre la línea.

-   Tiros cortos, arcos cortos y pausas cortas.

-   Tiros medios, arcos medios y pausas medias.

-   Tiros largos, arcos largos y pausas largas.

### La parada de la caña

Cuando para la caña, la curva o retraso que esta tenia se pierde y esta se endereza y se curva nuevamente en la dirección opuesta, hacia el objetivo y finalmente recupera su posición de reposo. Esta segunda curva o contra flexión, hacia el objetivo se llama Faz de rebote y en la dirección que esta se descargue, se proyectara la línea, siempre y cuando la línea venga alineada al objetivo durante todo el arco de lanzamiento, producto del control que se tiene en la trayectoria de la puntera.

Con una parada apropiada, lograra una buena transferencia de energía de la caña a la línea y podrá formar el loop, ya que la línea se adelanta a la caña producto de la parada. Si alguno de estos principios no estuvieran presentes a la hora de construir un lanzamiento, sencillamente este no sería efectivo. El conocimiento que de cada uno de los principios ayudara a elegir el arco de lanzamiento y el loop apropiado, la trayectoria del mismo, le dará más precisión, mejor presentación, menor fatiga y menos problemas, asustara mucho menos peces y por ende pescara más, ya que permitirá que se destaque la mosca y no el pescador y su equipo con movimientos ampulosos e innecesarios.

### Ejecicios de lanzamiento

En la pesca con mosca, hay cinco pilares fundamentales relacionados con la mecánica de lanzamiento. Cuando un principiante se familiariza con estos conceptos, puede aprender de manera más fácil y efectiva diferentes tipos de lanzamientos o 'casts'. Dominar estos lanzamientos es esencial, ya que se adaptan a diversas situaciones que pueden presentarse durante la pesca. Para lograr esto, el curso te brinda practicas centradas en los siguientes ejercicios

|                                                         |                                                                               |
|----------------------------------|--------------------------------------|
| Roll cast aéreo.                                        | Lanzamiento a distancia con double haul.                                      |
| Levante y tendido.                                      | Correcciones aéreas.                                                          |
| Cast elíptico o Belga                                   | Configuración del equipo.                                                     |
| Línea en vuelo con loops estrechos, medianos y amplios. | Nudos básicos.                                                                |
| Presentación de la mosca y precisión.                   | Confección, proporciones y tipos de leaders.                                  |
| Pick up roll.                                           | Orientación sobre los ámbitos de pesca elegidos por el alumno.                |
| Lanzamiento a distancia con línea pisada.               | Orientación sobre las moscas utilizadas en los diferentes ámbitos y especies. |
